name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: ls
      run: ls -l
    - name: hello
      run: echo hello  
    - name: version
      run: ./gradlew -v
    - name: build
      run: ./gradlew assembleRelease
    - name: ls
      run: ls -l
    - name: compileReleaseSource
      run: ./gradlew compileReleaseSource
    - name: ls build
      run: ls  -l build
    - name: ls app
      run: ls  -l app
    - name: ls
      run: ls   -l  app/build/outputs/apk/
    - name: ls
      run: ls   -l  build/outputs/apk
    - name: ls
      run: ls   -l  /app/build/outputs/apk/debug
    - name: ls
      run: ls   -l  /app/build/outputs/apk/release 
     
